name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-Linter
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r Streamlit/requirements.txt

      - name: Clear Streamlit Cache
        run: streamlit cache clear || true

      - name: Restart Streamlit App
        run: |
          pkill -f Streamlit.py || true
          nohup streamlit run Streamlit/Streamlit.py &

      - name: Sleep to Allow App Start
        run: sleep 10  # Wait 10 seconds for the app to restart
