name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"  # Your Python version

    - name: Install Dependencies
      run: |
        pip install -r Streamlit/requirements.txt  # Full path to your requirements.txt

    - name: Run Streamlit App
      run: |
        nohup streamlit run Streamlit/Streamlit.py &  # Full path to your Streamlit app
