name: Run Kaggle Notebook

on:
  push:
    branches:
      - main
  schedule:
    # This schedule is set to run daily at 10:30 AM UTC (4:00 PM IST).
    # YouTube API updates video statistics data between 12 PM and 3 PM IST.
    # Setting the schedule to 4 PM IST ensures that the latest data is available 
    # before the Kaggle notebook execution starts.
    - cron: '30 10 * * *'  # Runs daily at 10:30 AM UTC (4:00 PM IST)

jobs:
  kaggle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Upload Notebook to Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          kaggle kernels push -p Streamlit/

      - name: Check Kaggle Kernel Status
        run: kaggle kernels status darshanabk/devops-youtube-trends

      - name: Download Output
        run: kaggle kernels output darshanabk/devops-youtube-trends -p output/
