[theme]
# Default theme mode (light or dark)
base="light" # Can be "light" or "dark"

# Light theme settings
primaryColor="#4682B4" # Steel Blue accent
backgroundColor="#FFFFFF" # White background
secondaryBackgroundColor="#F0F2F6" # Light grey sidebar
textColor="#000000" # Black text

# Dark theme settings
[theme.dark]
primaryColor="#4682B4" # Steel Blue accent
backgroundColor="#0E1117" # Dark background
secondaryBackgroundColor="#262730" # Dark grey sidebar
textColor="#FFFFFF" # White text

# Custom Colors for Visualizations
[custom]
redColor="#FF4B4B" # Red for negative values
greenColor="#32CD32" # Lime Green for positive values
blueShades=["#00008B", "#0000CD", "#4169E1", "#4682B4", "#1E90FF"]  # Dark Blue to Light Blue
orangeShades=["#8B4513", "#D2691E", "#FF8C00", "#FFA500", "#FFD700"]  # Dark Orange to Gold

# Enable user toggle for theme selection
[client]
toolbarMode = "auto" # "auto" allows users to switch between themes
