[theme]
base = "dark" # Can be "light" or "dark"
primaryColor = "#4682B4" # Steel Blue accent
backgroundColor = "#FFFFFF" # White background
secondaryBackgroundColor = "#F0F2F6" # Light grey sidebar
textColor = "#000000" # Black text

[client]
toolbarMode = "auto" # Allows users to switch between themes

